### ISSUE TITLE
I got $oa->getClickId(); value false

### ISSUE THREAD

**Issue by ankita1612** [onlineactivitybv/php-advertiserpostback#1]
I installed composer and run composer.json in command prompt. it worked fine.
but when I run example I get value of following code to false
 $clickId = $oa->getClickId();
  var_dump($clickId);
///output get "false"  in var_dump
![image](https://user-images.githubusercontent.com/29705595/35853091-9c369686-0b52-11e8-9b7c-a5e53747cef7.png)

**Comment by blaaat** [comment]
did you add the ?oa_clickid=TEST parameter?

**Comment by blaaat** [comment]
Clarified example and added some [docs](doc/postbackconcept.md) in master.
